### PR TITLE
[Windows] Add external library

### PR DESCRIPTION
**Pull request by SeoHyungjun**
- Added external library mman-win32 and iniparser codes.
- Openblas dll and dll.a have been compressed and added.

Signed-off-by: SeoHyungjun <hyungjun.seo@samsung.com>

### CODE REVIEW

**Review by myungjoo — COMMENTED** [review]
Fetch the license file from the upstream (iniparser). It's required legally.
Or.. I'd recommend to have a file like https://github.com/ndevilla/iniparser/archive/refs/tags/v4.1.zip instead of this.

**Comment by SeoHyungjun** [comment]
In the case of iniparser, the LICENSE file exists in the github repo, so the file was added. (https://github.com/ndevilla/iniparser/blob/master/LICENSE)

However, in the case of mman-win32, it is stated as MIT License, but the file does not exist. (https://github.com/alitrack/mman-win32)

In this case, can I just specify the github link and the MIT License in README.md?

**Comment by myungjoo** [comment]
> In the case of iniparser, the LICENSE file exists in the github repo, so the file was added. (https://github.com/ndevilla/iniparser/blob/master/LICENSE)

Uh.. you didn't add it.


> However, in the case of mman-win32, it is stated as MIT License, but the file does not exist. (https://github.com/alitrack/mman-win32)
> 
> In this case, can I just specify the github link and the MIT License in README.md?

you don't have the files of mman-win32 in this PR anyway.

**Comment by SeoHyungjun** [comment]
I did not reflect the work done in the Local Repo.
So I added the changes again and pushed.

**Review by DonghakPark — COMMENTED** [review]
At some files there was ```No newline at end of file``` warning

according to ```POSIX``` style add newline at EOF is recommanded

**Comment by SeoHyungjun** [comment]
@DonghakPark  Added newline at end.

**Review by myungjoo — APPROVED** [review]

**Pull request merged**
